// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A simple API to learn how to write OpenAPI Specification",
    "title": "Simple API",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/accounts": {
      "get": {
        "description": "Returns a list containing all accounts.",
        "summary": "Gets some accounts",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "description": "PK part 1",
            "name": "id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "format": "string",
            "description": "PK part 2",
            "name": "name",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A list of Accounts",
            "schema": {
              "type": "array",
              "items": {
                "required": [
                  "id",
                  "name"
                ],
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}`))
}
